W8less
BravoCMS/bravo-template-example pull request #3
Opened 2019-06-17 17:53 UTC by w8less

добавил описание module/article(s) для docs/ru+en
пофиксил неточности

2019-06-18 06:18 UTC, lame07 requested changes

2019-06-18 06:18 UTC, lame07 commented on docs/en/modules/articles.md
> +## `<{$articles}>` displays an array of all articles
<{$articles}> Эту переменную я думаю мы уберем из шаблона.

т.к. в шаблоне может быть необходимость сетки по 2/3/4 элемента, соответственно элементов на странице может быть 4/6/8/10/12 и т.д.. И это должно определяться шаблоном под дизайн. Получение элементов в списковых модулях будет происходить конструкциями типа:

<{get_blog_articles 'articles' 'pagination' by="12" page_query}>

Списковые модули должны все так работать

2019-06-18 06:18 UTC, lame07 commented on docs/en/modules/articles.md
> +## `<{$articles}>` displays an array of all articles
в данном случае нужно добавить описание, что сначала нужно получить элементы, а потом уже можно их использовать из переменной <{get_blog_articles **'articles'** 'pagination' by="12" page_query}> **<{$articles}>**

2019-06-21 20:57 UTC, w8less commented
<{get... }> изменил в articles.md

2019-06-24 13:05 UTC, lame07 approved these changes

2019-06-24 13:05 UTC, merged